In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

np1 = np.array([1,2,3,4])
np2 = np.array((5,6,7,8))

print(np1)
print(np2)
print(type(np1),type(np2))

[1 2 3 4]
[5 6 7 8]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [12]:
np3 = np.arange(0,31,2)
print(np3,'\n')

np4 = np.linspace(1,15,3)
print(np4,'\n')

np5 = np.zeros((5,))
print(np5,'\n')

np6 = np.ones((5,))
print(np6,'\n')

np7 = np.ones((5,2))
print(np7,'\n')

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30] 

[ 1.  8. 15.] 

[0. 0. 0. 0. 0.] 

[1. 1. 1. 1. 1.] 

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 



In [9]:
listdata = [[1,2,3,4,5],[6,7,8,9,10]]

np8 = np.array(listdata)
print(np8)
print('維度',np8.ndim)
print('形狀',np8.shape)
print('數量',np8.size)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
維度 2
形狀 (2, 5)
數量 10


In [14]:
np9 = np.arange(1,21)
print(np9,'\n')

np10 = np9.reshape(4,5)
print(np10)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [16]:
np10 = np.arange(0,9)

print(np10,'\n')

print(np10[0],'\n')

print(np10[8],'\n')

print(np10[1:8],'\n')

print(np10[1:8:2],'\n')

print(np10[8:1:-1],'\n')

print(np10[:],'\n')

print(np10[:4],'\n')

print(np10[4:],'\n')

[0 1 2 3 4 5 6 7 8] 

0 

8 

[1 2 3 4 5 6 7] 

[1 3 5 7] 

[8 7 6 5 4 3 2] 

[0 1 2 3 4 5 6 7 8] 

[0 1 2 3] 

[4 5 6 7 8] 



In [18]:
np11 = np.arange(1,21).reshape(5,4)

np11
np11[0,2]
np11[1,2]

print(np11[1:3,2],'\n')

print(np11[1:3,1:3],'\n')

print(np11[::2,::2],'\n')

print(np11[:,2],'\n')

print(np11[1,:],'\n')

print(np11[:,:],'\n')

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[ 7 11] 

[[ 6  7]
 [10 11]] 

[[ 1  3]
 [ 9 11]
 [17 19]] 

[ 3  7 11 15 19] 

[5 6 7 8] 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]] 



In [24]:
print('1.產生2*3 0~1之間的隨機浮點數\n',
      np.random.rand(2,3))
print('2.產生2*3常態分佈的隨機浮點數\n',
      np.random.randn(2,3))
print('3.產生0~4(不含5)隨機整數\n',
      np.random.randint(5))
print('4.產生2~4(不含5)5個隨機整數\n',
      np.random.randint(2,5,[5]))
print('5.產生3個 0~1之間的隨機浮點數\n',
      np.random.random(3),'\n',
      np.random.random_sample(3),'\n',
      np.random.sample(3))

1.產生2*3 0~1之間的隨機浮點數
 [[0.19229186 0.80617469 0.13866858]
 [0.683582   0.58847508 0.41027105]]
2.產生2*3常態分佈的隨機浮點數
 [[-0.33266893  0.55803483 -0.79558898]
 [-0.01471921 -1.04444052  1.68007453]]
3.產生0~4(不含5)隨機整數
 1
4.產生2~4(不含5)5個隨機整數
 [3 3 2 3 2]
5.產生3個 0~1之間的隨機浮點數
 [0.73935559 0.10548337 0.61746113] 
 [0.08604426 0.5952182  0.14171179] 
 [0.71433176 0.24405065 0.63321744]


In [27]:
# 增加一個變數，將scores.csv匯入

np12 = np.genfromtxt('scores.csv', delimiter=',',skip_header=1)

#用shape看一下檔案

print(np12.shape)

#呼叫NA

np12

ValueError: Some errors were detected !
    Line #35 (got 16 columns instead of 1)
    Line #139 (got 4 columns instead of 1)
    Line #170 (got 2 columns instead of 1)
    Line #276 (got 3 columns instead of 1)
    Line #295 (got 6 columns instead of 1)
    Line #296 (got 3 columns instead of 1)
    Line #319 (got 4 columns instead of 1)
    Line #332 (got 4 columns instead of 1)
    Line #345 (got 4 columns instead of 1)
    Line #358 (got 4 columns instead of 1)
    Line #371 (got 4 columns instead of 1)
    Line #384 (got 4 columns instead of 1)
    Line #397 (got 4 columns instead of 1)
    Line #410 (got 4 columns instead of 1)
    Line #428 (got 4 columns instead of 1)
    Line #435 (got 4 columns instead of 1)
    Line #444 (got 4 columns instead of 1)
    Line #453 (got 4 columns instead of 1)
    Line #479 (got 4 columns instead of 1)
    Line #486 (got 4 columns instead of 1)
    Line #493 (got 4 columns instead of 1)
    Line #505 (got 4 columns instead of 1)
    Line #512 (got 4 columns instead of 1)
    Line #519 (got 4 columns instead of 1)
    Line #531 (got 4 columns instead of 1)
    Line #538 (got 4 columns instead of 1)
    Line #545 (got 4 columns instead of 1)
    Line #568 (got 4 columns instead of 1)
    Line #575 (got 4 columns instead of 1)
    Line #582 (got 4 columns instead of 1)
    Line #589 (got 4 columns instead of 1)
    Line #596 (got 4 columns instead of 1)
    Line #603 (got 4 columns instead of 1)
    Line #615 (got 4 columns instead of 1)
    Line #624 (got 8 columns instead of 1)
    Line #625 (got 3 columns instead of 1)
    Line #633 (got 4 columns instead of 1)
    Line #640 (got 4 columns instead of 1)
    Line #665 (got 4 columns instead of 1)
    Line #680 (got 4 columns instead of 1)
    Line #696 (got 4 columns instead of 1)
    Line #703 (got 4 columns instead of 1)
    Line #710 (got 4 columns instead of 1)
    Line #733 (got 4 columns instead of 1)
    Line #751 (got 4 columns instead of 1)
    Line #764 (got 4 columns instead of 1)
    Line #777 (got 4 columns instead of 1)
    Line #796 (got 3 columns instead of 1)
    Line #818 (got 2 columns instead of 1)
    Line #839 (got 5 columns instead of 1)
    Line #1151 (got 2 columns instead of 1)
    Line #1225 (got 2 columns instead of 1)
    Line #1251 (got 6 columns instead of 1)
    Line #1252 (got 3 columns instead of 1)
    Line #1260 (got 6 columns instead of 1)
    Line #1261 (got 3 columns instead of 1)
    Line #1348 (got 2 columns instead of 1)
    Line #1380 (got 6 columns instead of 1)
    Line #1388 (got 6 columns instead of 1)
    Line #1397 (got 6 columns instead of 1)
    Line #1665 (got 248 columns instead of 1)
    Line #1695 (got 2 columns instead of 1)
    Line #1705 (got 3 columns instead of 1)
    Line #1709 (got 3 columns instead of 1)
    Line #1713 (got 3 columns instead of 1)
    Line #1717 (got 3 columns instead of 1)
    Line #1721 (got 3 columns instead of 1)
    Line #1725 (got 3 columns instead of 1)